unpackaged/main/default/objects/Account/fields/CL_AccountIDInSF2__c.field-meta.xml
<CustomField>
    <fullName>CL_AccountIDInSF2__c</fullName>
    <label>Account ID in SF2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_CS1InBearbeitung__c.field-meta.xml
<CustomField>
    <fullName>CL_CS1InBearbeitung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CS1 in Bearbeitung</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_CS2InBearbeitung__c.field-meta.xml
<CustomField>
    <fullName>CL_CS2InBearbeitung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CS2 in Bearbeitung</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_DrucksteuerungSMVBelegeVG1__c.field-meta.xml
<CustomField>
    <fullName>CL_DrucksteuerungSMVBelegeVG1__c</fullName>
    <label>Drucksteuerung SMV Belege  (VG1)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ohne Gültigkeit</fullName>
                <default>true</default>
                <label>ohne Gültigkeit</label>
            </value>
            <value>
                <fullName>pro Kunde 1 SMV</fullName>
            </value>
            <value>
                <fullName>pro Produkt 1 SMV</fullName>
            </value>
            <value>
                <fullName>pro Rechnungsnummer 1 SMV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_Firmenstatus__c.field-meta.xml
<CustomField>
    <fullName>CL_Firmenstatus__c</fullName>
    <defaultValue>&quot;Lead&quot;</defaultValue>
    <label>Firmenstatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
                <default>true</default>
                <label>Lead</label>
            </value>
            <value>
                <fullName>Potenzial</fullName>
            </value>
            <value>
                <fullName>non-Debitor Kunde</fullName>
            </value>
            <value>
                <fullName>Debitor Kunde</fullName>
            </value>
            <value>
                <fullName>Konzerndebitor</fullName>
            </value>
            <value>
                <fullName>Sonstige</fullName>
            </value>
            <value>
                <fullName>Debitor-Kunde</fullName>
                <isActive>false</isActive>
                <label>Debitor-Kunde</label>
            </value>
            <value>
                <fullName>Kunde</fullName>
                <isActive>false</isActive>
                <label>Kunde</label>
            </value>
            <value>
                <fullName>non-Debitor-Kunde</fullName>
                <isActive>false</isActive>
                <label>non-Debitor-Kunde</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_GeplAuftragsvolumenVG1__c.field-meta.xml
<CustomField>
    <fullName>CL_GeplAuftragsvolumenVG1__c</fullName>
    <label>Gepl. Auftragsvolumen (VG1)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_VertriebsgesellschaftVG1__c.field-meta.xml
<CustomField>
    <fullName>CL_VertriebsgesellschaftVG1__c</fullName>
    <label>Vertriebsgesellschaft (VG1)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ambient-TV Sales &amp; Servic</fullName>
            </value>
            <value>
                <fullName>BlowUP Media GmbH</fullName>
            </value>
            <value>
                <fullName>Business Advertising GmbH</fullName>
            </value>
            <value>
                <fullName>DERG Vertriebs GmbH</fullName>
            </value>
            <value>
                <fullName>DSA Schuldisplay GmbH</fullName>
            </value>
            <value>
                <fullName>DSM Decaux GmbH</fullName>
            </value>
            <value>
                <fullName>DSM DeutscheStädte-Medien</fullName>
            </value>
            <value>
                <fullName>DSM Werbeträger GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>ECE flatmedia GmbH</fullName>
            </value>
            <value>
                <fullName>Edgar Ambient Media Group GmbH</fullName>
            </value>
            <value>
                <fullName>Grapevine Marketing GmbH</fullName>
            </value>
            <value>
                <fullName>Hoffmann City Media GmbH&amp;</fullName>
            </value>
            <value>
                <fullName>INFOSCREEN GmbH</fullName>
            </value>
            <value>
                <fullName>Interactive Media CCSP</fullName>
            </value>
            <value>
                <fullName>Lunenburg und Partner Gmb</fullName>
            </value>
            <value>
                <fullName>MBR Targeting GmbH</fullName>
            </value>
            <value>
                <fullName>Media-Direktservice GmbH</fullName>
            </value>
            <value>
                <fullName>MediaSelect Media-Agentur</fullName>
            </value>
            <value>
                <fullName>Neo Advertising GmbH</fullName>
            </value>
            <value>
                <fullName>Omnea GmbH</fullName>
            </value>
            <value>
                <fullName>Outsite Media GmbH</fullName>
            </value>
            <value>
                <fullName>PosterSelect Media-Agent.</fullName>
            </value>
            <value>
                <fullName>RegioHelden GmbH</fullName>
            </value>
            <value>
                <fullName>Retail Media GmbH</fullName>
            </value>
            <value>
                <fullName>Seeding Alliance GmbH</fullName>
            </value>
            <value>
                <fullName>SIGN YOU mediascreen GmbH</fullName>
            </value>
            <value>
                <fullName>SMD Werbeträger GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>SRG Werbeträger GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>Ströer Aussenwerbung GmbH</fullName>
            </value>
            <value>
                <fullName>Ströer Content Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_ZahlungskonditionenVG1__c.field-meta.xml
<CustomField>
    <fullName>CL_ZahlungskonditionenVG1__c</fullName>
    <label>Zahlungskonditionen (VG1)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>14 Tage ab Re.dat. 2% Skto., 45 Tage ohne Abzug</fullName>
            </value>
            <value>
                <fullName>14 Tagen ab Rechnungsdatum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>14 Tg. ab Leist.beg. 2%Skt.;30 ab Leist.beg. o.Ab</fullName>
            </value>
            <value>
                <fullName>14 Tg. bis Leist.beg. 2% Skt, 30 Tg. o. Abz. ab Le</fullName>
            </value>
            <value>
                <fullName>30 Tage ab Leistungsdatum mit 2% Skonto</fullName>
            </value>
            <value>
                <fullName>30 Tage ab Leistungsdatum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>4 Tage nach Rechnungsdatum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>45 Tagen ab Rechnungsdatum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>8 Tage ab Rechnugsdatum 2 % Skt.; 30 Tage o. Abzug</fullName>
            </value>
            <value>
                <fullName>8 Tage ab Rechnungsdatum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>90 Tage ab Leistungsdatum mit 2% Skonto</fullName>
            </value>
            <value>
                <fullName>90 Tage ab Rechnungsdatum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>Vorauskasse</fullName>
            </value>
            <value>
                <fullName>Fällig zum 1. Tag des Leistungszeitraum ohne Abzug</fullName>
            </value>
            <value>
                <fullName>14 Tage 3%, 20/2%, 30 net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CL_ZurBearbeitungGesperrt__c.field-meta.xml
<CustomField>
    <fullName>CL_ZurBearbeitungGesperrt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Zur Bearbeitung gesperrt</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LKM_EmailZentrale__c.field-meta.xml
<CustomField>
    <fullName>LKM_EmailZentrale__c</fullName>
    <label>Email Zentrale</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LKM_IndustryOberbranche__c.field-meta.xml
<CustomField>
    <fullName>LKM_IndustryOberbranche__c</fullName>
    <description>Achtung: Abhängige Auswahllisten 4 Ebenen</description>
    <label>Oberbranche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenturen</fullName>
            </value>
            <value>
                <fullName>Bank / Finanzdienstleistung / Versicherung</fullName>
            </value>
            <value>
                <fullName>Beauty / Kosmetik / Wellness</fullName>
            </value>
            <value>
                <fullName>Bildung</fullName>
            </value>
            <value>
                <fullName>Dienstleistung</fullName>
            </value>
            <value>
                <fullName>Elektronik / IT</fullName>
            </value>
            <value>
                <fullName>Freizeit</fullName>
            </value>
            <value>
                <fullName>Gastronomie</fullName>
            </value>
            <value>
                <fullName>Handel / Einkauf</fullName>
            </value>
            <value>
                <fullName>KFZ</fullName>
            </value>
            <value>
                <fullName>Lokale Medien</fullName>
            </value>
            <value>
                <fullName>Medizin / Gesundheit</fullName>
            </value>
            <value>
                <fullName>Öffentlichkeit</fullName>
            </value>
            <value>
                <fullName>Produzierende Industrie</fullName>
            </value>
            <value>
                <fullName>Recht</fullName>
            </value>
            <value>
                <fullName>Ströer-Branchen</fullName>
            </value>
            <value>
                <fullName>Tourismus</fullName>
            </value>
            <value>
                <fullName>Transport / Logistik</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LKM_IndustryUnterbranche__c.field-meta.xml
<CustomField>
    <fullName>LKM_IndustryUnterbranche__c</fullName>
    <label>Unterbranche</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LKM_IndustryOberbranche__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abschleppdienst</fullName>
            </value>
            <value>
                <fullName>Agentur Sonstige</fullName>
            </value>
            <value>
                <fullName>Anwälte</fullName>
            </value>
            <value>
                <fullName>Apotheken</fullName>
            </value>
            <value>
                <fullName>Architektur</fullName>
            </value>
            <value>
                <fullName>Ärzte</fullName>
            </value>
            <value>
                <fullName>Autohaus</fullName>
            </value>
            <value>
                <fullName>Autohersteller</fullName>
            </value>
            <value>
                <fullName>Autovermietung</fullName>
            </value>
            <value>
                <fullName>Banken Sonstige</fullName>
            </value>
            <value>
                <fullName>Bars / Diskotheken</fullName>
            </value>
            <value>
                <fullName>Baumärkte</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
            <value>
                <fullName>Beauty / Kosmetik / Wellness Sonstige</fullName>
            </value>
            <value>
                <fullName>Behörden / Verwaltung</fullName>
            </value>
            <value>
                <fullName>Beratung / Coaching</fullName>
            </value>
            <value>
                <fullName>Bestattung</fullName>
            </value>
            <value>
                <fullName>Brauerei / Getränkehersteller</fullName>
            </value>
            <value>
                <fullName>Caritative Organisationen</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Dienstleistung Sonstige</fullName>
            </value>
            <value>
                <fullName>Drogerie</fullName>
            </value>
            <value>
                <fullName>Druckereien</fullName>
            </value>
            <value>
                <fullName>Einkaufszentrum</fullName>
            </value>
            <value>
                <fullName>Einzelgastronomie</fullName>
            </value>
            <value>
                <fullName>Elektronik- / IT-Märkte</fullName>
            </value>
            <value>
                <fullName>Elektronik / IT Sonstige</fullName>
            </value>
            <value>
                <fullName>Energieversorger</fullName>
            </value>
            <value>
                <fullName>Entsorgungsbetriebe</fullName>
            </value>
            <value>
                <fullName>Erotik</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/persistent329Test.cls
/**
 * Created by fabiankramer on 26.05.21.
 */

//@IsTest
public with sharing class persistent329Test {

    //@TestSetup
    public static void insertAccount(){

        delete [SELECT Id FROM Account WHERE Name LIKE 'Dummy Account - %' LIMIT 100];

        List<Account> accountList = new List<Account>();

        Account a1 =  new Account(
                Name = 'Dummy Account - Case 100',
                CL_AccountIDInSF2__c = '0011r00002EdYJ0AAN',
                CL_Firmenstatus__c = 'Debitor Kunde',
                CL_CS1InBearbeitung__c = false, // wegen Validierungsregel LKM_AlleVierVGFelder
                CL_CS2InBearbeitung__c = false, // wegen Validierungsregel  LKM_AlleVierVGFelder
                CL_ZurBearbeitungGesperrt__c = false,
                ShippingPostalCode = '74321',
                ShippingCity = 'test',
                BillingCity = 'test',
                BillingPostalCode = '74321',
                BillingStateCode = 'BW',
                BillingCountry = 'Deutschland',
                LKM_EmailZentrale__c = 'fabian.kramer@fk-sd.de',
                Phone = '+491754101967',
                RecordTypeId = '0121r000000BYKgAAO',
                CL_GeplAuftragsvolumenVG1__c = 999999,
                CL_DrucksteuerungSMVBelegeVG1__c = 'ohne Gültigkeit',
                CL_VertriebsgesellschaftVG1__c = 'Ambient-TV Sales & Servic',
                CL_ZahlungskonditionenVG1__c = '14 Tage ab Re.dat. 2% Skto., 45 Tage ohne Abzug',
                Type = 'Werbungtreibender',
                LKM_IndustryOberbranche__c = 'Dienstleistung',
                LKM_IndustryUnterbranche__c = 'Dienstleistung Sonstige',
                CL_Antrag_CS2__c = 'Neu',
                CL_GecleartCS2__c = null
                //CL_HelperDebitorenNeuAnlageausSF2__c =true
        );

        Account a2 =  new Account(
                Name = 'Dummy Account - Case 200',
                CL_AccountIDInSF2__c = '0011r00002EdYJ0AAN',
                CL_Firmenstatus__c = 'Debitor Kunde',
                CL_CS1InBearbeitung__c = false, // wegen Validierungsregel LKM_AlleVierVGFelder
                CL_CS2InBearbeitung__c = true, // wegen Validierungsregel  LKM_AlleVierVGFelder
                CL_ZurBearbeitungGesperrt__c = false,
                ShippingPostalCode = '74321',
                ShippingCity = 'test',
                BillingCity = 'test',
                BillingPostalCode = '74321',
                BillingStateCode = 'BW',
                BillingCountry = 'Deutschland',
                LKM_EmailZentrale__c = 'fabian.kramer@fk-sd.de',
                Phone = '+491754101967',
                RecordTypeId = '0121r000000BYKgAAO',
                CL_GeplAuftragsvolumenVG1__c = 999999,
                CL_DrucksteuerungSMVBelegeVG1__c = 'ohne Gültigkeit',
                CL_VertriebsgesellschaftVG1__c = 'Ambient-TV Sales & Servic',
                CL_ZahlungskonditionenVG1__c = '14 Tage ab Re.dat. 2% Skto., 45 Tage ohne Abzug',
                Type = 'Werbungtreibender',
                LKM_IndustryOberbranche__c = 'Dienstleistung',
                LKM_IndustryUnterbranche__c = 'Dienstleistung Sonstige',
                CL_Antrag_CS2__c = 'Neu',
                CL_GecleartCS2__c = null,
                CL_EMail__c = 'fabian_kramer@persistent.com',
                CL_HelperEmailangefordertVon__c = 'fabian_kramer@persistent.com'
                //CL_HelperDebitorenNeuAnlageausSF2__c =true
        );

        accountList.add(a1);
        accountList.add(a2);
        insert accountList;

    }

    //@IsTest
    public static void updateAccount1(){
        Account acc = [SELECT Id  FROM Account WHERE Name = 'Dummy Account - Case 100' LIMIT 1][0];
        //Test.startTest();
        acc.CL_GecleartCS2__c = System.Today();
        acc.CL_Antrag_CS2__c = 'Ändern';
        update acc;
        //Test.startTest();
    }

    //@IsTest
    public static void updateAccount2(){
        Account acc = [SELECT Id  FROM Account WHERE Name = 'Dummy Account - Case 200' LIMIT 1][0];
        //Test.startTest();
        acc.CL_Antrag_CS2__c = 'Ändern';
        acc.CL_AbgelehnteNeuanlageCS1CS2__c = true;
        update acc;
        //Test.startTest();
    }


}